// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4ER0M-NRclAHnSFNGqZsHm7-TkwU3SE',
    appId: '1:86895289380:web:8b7a23ea6348d6e632e4b1',
    messagingSenderId: '86895289380',
    projectId: 'galexi-eebbe',
    authDomain: 'galexi-eebbe.firebaseapp.com',
    storageBucket: 'galexi-eebbe.firebasestorage.app',
    measurementId: 'G-PDQKQ60BD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWEepCPLLtVTmU9PJ_Lnv4P45ZBwem6fQ',
    appId: '1:86895289380:android:46d110dca2c6ad9d32e4b1',
    messagingSenderId: '86895289380',
    projectId: 'galexi-eebbe',
    storageBucket: 'galexi-eebbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMhgD5PBajH9CKLU_LNiMgvQwCJLDpxIM',
    appId: '1:86895289380:ios:9ccbce46c82bf3b332e4b1',
    messagingSenderId: '86895289380',
    projectId: 'galexi-eebbe',
    storageBucket: 'galexi-eebbe.firebasestorage.app',
    iosBundleId: 'com.example.aurexMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMhgD5PBajH9CKLU_LNiMgvQwCJLDpxIM',
    appId: '1:86895289380:ios:9ccbce46c82bf3b332e4b1',
    messagingSenderId: '86895289380',
    projectId: 'galexi-eebbe',
    storageBucket: 'galexi-eebbe.firebasestorage.app',
    iosBundleId: 'com.example.aurexMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN4ER0M-NRclAHnSFNGqZsHm7-TkwU3SE',
    appId: '1:86895289380:web:e61aa17d9ed88b4932e4b1',
    messagingSenderId: '86895289380',
    projectId: 'galexi-eebbe',
    authDomain: 'galexi-eebbe.firebaseapp.com',
    storageBucket: 'galexi-eebbe.firebasestorage.app',
    measurementId: 'G-1ZMQ38GQVJ',
  );
}
